version: '3.4'

services:
  webapi:
    image: ${DOCKER_REGISTRY-}webapi
    build:
      context: .
      dockerfile: Presentation/Dockerfile

  webapiredis:
    image: redis
    restart: always
    ports:
     - "6379:6379"
    environment:
     - ALLOW_EMPTY_PASSWORD=yes

  webapimssql:
    image: mcr.microsoft.com/mssql/server:latest
    restart: always
    ports:
     - "1435:1433"
    environment:
            SA_PASSWORD: "yourStrong(!)Password"
            ACCEPT_EULA: "Y"       